# [OWNER: Dev 3 — P2 Requirements Agent]
"""Proposal — the customer-facing PDF deliverable generated by P2.

A Proposal is the formal document sent to the lead.  It wraps a Quotation
(line items + pricing) with a professional cover, scope section, timeline,
and terms — all rendered to PDF via ReportLab / WeasyPrint.

Relationship:
  Lead → [Conversations] → RequirementsDoc → Quotation → Proposal (PDF)

The Proposal PDF is stored on disk and its path written here.  Future:
  upload to S3/GCS and store a signed URL.
"""

from datetime import datetime
from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel


class ProposalStatus(StrEnum):
    GENERATING = "generating"     # Worker building the PDF
    READY = "ready"               # PDF available for download
    SENT = "sent"                 # Shared with the lead (link / email)
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    EXPIRED = "expired"           # e.g. validity period passed


class Proposal(BaseModel):
    id: UUID
    quotation_id: UUID
    requirements_doc_id: UUID | None = None   # Source requirements
    lead_id: UUID
    agent_id: UUID

    title: str
    executive_summary: str = ""

    # Validity window shown on the document
    valid_days: int = 30

    status: ProposalStatus = ProposalStatus.GENERATING

    # Absolute path to PDF on disk (or future object-store key)
    pdf_path: str | None = None

    # Short-lived download token (rotated on each view request)
    download_token: str | None = None

    # Odoo quotation ID after ERP sync (future)
    odoo_order_id: int | None = None

    created_at: datetime
    updated_at: datetime
