# [OWNER: Akash — P2 Requirements Agent]
"""Quotation — a structured price estimate generated from a Conversation.

In v3.0 this is the lightweight internal record; the customer-facing deliverable
is a Proposal (PDF) generated by the P2 Requirements Agent and stored in
src/domain/entities/proposal.py.

Quotation ↔ Proposal relationship:
  - A Quotation stores the raw line items and total.
  - A Proposal wraps a Quotation with formatted PDF, linked RequirementsDoc,
    and is what gets sent to the lead.
"""

from datetime import datetime
from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, Field


class QuotationStatus(StrEnum):
    DRAFT = "draft"
    UNDER_REVIEW = "under_review"   # SALES_MANAGER reviewing before send
    SENT = "sent"
    ACCEPTED = "accepted"
    REJECTED = "rejected"


class LineItem(BaseModel):
    description: str
    quantity: float = 1.0
    unit_price: float
    total: float = Field(default=0.0)

    def model_post_init(self, __context: object) -> None:
        self.total = round(self.quantity * self.unit_price, 2)


class Quotation(BaseModel):
    id: UUID
    conversation_id: UUID
    lead_id: UUID
    agent_id: UUID
    title: str
    line_items: list[LineItem] = []
    notes: str = ""
    total_amount: float = 0.0
    currency: str = "USD"
    status: QuotationStatus = QuotationStatus.DRAFT

    # Path to generated .docx file on disk (legacy; Proposal generates PDF now)
    doc_path: str | None = None

    # Qdrant vector ID for similarity matching against past quotations
    vector_id: str | None = None

    # Linked proposal (UUID) once P2 generates the PDF
    proposal_id: UUID | None = None

    # Odoo sale order ID (populated after ERP sync — future)
    odoo_order_id: int | None = None

    created_at: datetime
    updated_at: datetime

    def compute_total(self) -> float:
        self.total_amount = round(sum(item.total for item in self.line_items), 2)
        return self.total_amount
