# [OWNER: Dev 2 — P1 Conversation Engine]
"""Suggestion — a single reply option generated by the P1 Conversation Engine.

The P1 pipeline produces SUGGESTION_COUNT (5) suggestions per inbound message.
The salesperson selects one (or types manually), and selection feedback is stored
in SuggestionEvent for A/B scoring and prompt improvement.

Structured output schema mirrors prompts/shared/output_schemas/suggestion_list_v1.json
"""

from datetime import datetime
from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, Field


class SuggestionTone(StrEnum):
    PROFESSIONAL = "professional"
    FRIENDLY = "friendly"
    EMPATHETIC = "empathetic"
    ASSERTIVE = "assertive"
    CONSULTATIVE = "consultative"


class SuggestionStrategy(StrEnum):
    DISCOVERY = "discovery"          # Ask clarifying questions
    VALUE_PROP = "value_proposition" # Highlight capabilities
    SOCIAL_PROOF = "social_proof"    # Reference past work
    URGENCY = "urgency"              # Time/capacity pressure
    NEGOTIATION = "negotiation"      # Address budget concerns


class Suggestion(BaseModel):
    id: UUID
    conversation_id: UUID
    message_id: UUID              # The inbound message this responds to
    lead_id: UUID

    # Rank 1 = most recommended by the model
    rank: int = Field(ge=1, le=5)

    strategy: SuggestionStrategy
    tone: SuggestionTone

    # Short preview shown in the UI card (≤120 chars)
    preview_text: str

    # Full message text ready to paste/send
    full_text: str

    # Estimated probability of advancing the lead (0.0–1.0)
    conversion_signal: float = Field(ge=0.0, le=1.0)

    # Which LLM provider generated this (gpt-4.1 | claude-sonnet-4-6 | vllm)
    generated_by: str = "gpt-4.1"

    # Intent label that triggered this generation
    intent_label: str | None = None

    created_at: datetime


class SuggestionEvent(BaseModel):
    """Tracks which suggestion was selected or if the agent typed manually.

    Used for:
    - Prompt A/B evaluation (eval_suite.yaml)
    - Conversion rate by strategy/tone
    - Training signal for future fine-tuning
    """

    id: UUID
    suggestion_id: UUID | None = None   # None means agent typed manually
    conversation_id: UUID
    lead_id: UUID
    agent_id: UUID

    selected: bool = False           # True = this suggestion was chosen
    manually_typed: bool = False     # True = agent ignored all suggestions

    # Time between suggestion delivery and selection (ms)
    response_time_ms: int | None = None

    created_at: datetime
