# [OWNER: Dev 1 — Data Foundation (P3)]
"""SQLAlchemy ORM model for Suggestion — PostgreSQL 17.

One row per suggestion generated by the P1 pipeline.
The pipeline always produces SUGGESTION_COUNT (5) rows per inbound message.
"""

import uuid

from sqlalchemy import Float, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import ENUM as PgEnum
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from src.domain.entities.suggestion import SuggestionStrategy, SuggestionTone
from src.infrastructure.db.base import Base
from src.infrastructure.db.models.mixins import TimestampMixin


class SuggestionModel(TimestampMixin, Base):
    __tablename__ = "suggestions"

    id: Mapped[str] = mapped_column(
        PGUUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    # FK to the conversation this suggestion belongs to
    conversation_id: Mapped[str] = mapped_column(
        PGUUID(as_uuid=False),
        ForeignKey("conversations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # FK to the specific customer message that triggered generation
    message_id: Mapped[str] = mapped_column(
        PGUUID(as_uuid=False),
        ForeignKey("messages.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Denormalised for fast lead-scoped queries (no cross-table join needed)
    lead_id: Mapped[str] = mapped_column(
        PGUUID(as_uuid=False), nullable=False, index=True
    )

    # Rank 1 = most recommended; always 1–5
    rank: Mapped[int] = mapped_column(Integer, nullable=False)

    strategy: Mapped[str] = mapped_column(
        PgEnum("discovery", "value_proposition", "social_proof", "urgency", "negotiation",
               name="suggestionstrategy", create_type=False),
        nullable=False,
    )
    tone: Mapped[str] = mapped_column(
        PgEnum("professional", "friendly", "empathetic", "assertive", "consultative",
               name="suggestiontone", create_type=False),
        nullable=False,
    )

    # Short card preview shown in the UI (≤120 chars)
    preview_text: Mapped[str] = mapped_column(Text, nullable=False)

    # Full reply text ready for the salesperson to paste/send
    full_text: Mapped[str] = mapped_column(Text, nullable=False)

    # Model-estimated probability of advancing the lead (0.0–1.0)
    conversion_signal: Mapped[float] = mapped_column(Float, nullable=False, default=0.5)

    # Which LLM provider generated this suggestion
    generated_by: Mapped[str] = mapped_column(String(64), nullable=False, default="gpt-4.1")

    # Intent class that triggered generation (nullable — set when available)
    intent_label: Mapped[str | None] = mapped_column(String(64), nullable=True)

    # created_at + updated_at from TimestampMixin
